version: 2
updates:
  # run Dependabot every Monday at 3 AM UTC
  - schedule:
      interval: weekly
      day: monday
      time: "03:00"
    package-ecosystem: "maven"
    # The directory where dependabot looks for pom.xml file
    directory: "/"
    update-type: "all"